### PR TITLE
Decentralized Payment Gateway

### PR DESCRIPTION
**Pull request by algonomad571**
This PR adds a decentralized payment gateway feature using the Solana blockchain and Anchor framework. The gateway allows users to transfer SOL between wallets by entering a recipient's address (UPI ID mapped to Solana) and an amount. The backend is powered by a Solana smart contract that handles the transfer, while the frontend provides a simple UI for input and transaction processing.

#### Includes:
- Solana smart contract for payment.
- Frontend integration with wallet adapter.

### CODE REVIEW

**Comment by algonomad571** [comment]
Closes issue #17

**Comment by Anandprafull** [comment]
You  haven't added any code? Why do you wanna merge it?? @muskan171105

**Comment by algonomad571** [comment]
I'm sorry I guess the code was not added. I will update the code and push it by EOD

**Comment by Anandprafull** [comment]
What's the update @muskan171105 ?

**Pull request closed without merging**
